# postgres/nopassword
version: '3.1'

services:
  redis:
    image: redis
    #    container_name: bee_dictionary_redis
    command: redis-server --requirepass UETDistribute!@#2019
    volumes:
      - /home/tuantmtb/Documents/data/uet-distribute-url/database/redis_data:/data
    restart: 'no'
    ports:
      - 6379:6379
